import { UserImage } from '../types';

export const applyHairstyle = async (
  userImage: UserImage,
  prompt: string
): Promise<string> => {
  try {
    const response = await fetch('/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ userImage, prompt }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      if (response.status === 429) {
        throw new Error("API quota exceeded. Please wait a moment and try again, or upgrade your plan.");
      }
      throw new Error(`Failed to generate hairstyle: ${errorText}`);
    }

    const data = await response.json();
    if (data.image) {
      return data.image;
    }

    throw new Error("No image was generated by the AI. Please try again.");
  } catch (error) {
    console.error("Error applying hairstyle:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate hairstyle: ${error.message}`);
    }
    throw new Error("An unknown error occurred while generating the hairstyle.");
  }
};